apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-sample
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.deployments-status: ""
spec:
  project: demo-deployment
  ignoreDifferences:
    - group: apps
      kind: Service
      name: ks-sample-dev
      namespace: user-deployments
      jqPathExpressions:
        - .spec.ports[] | select(.nodePort == 32000 )
  source:
    path: deployments/test
    repoURL: https://github.com/liujunhong5891/demo-user-deployments.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: user-deployments
  syncPolicy:
    automated:
      selfHeal: false   # 调试
      prune: true
    syncOptions:
      - CreateNamespace=true
