apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook
spec:
  service:
    ports:
      - port: 13000
        targetPort: 13000
  webhook:
    example:
      port: "13000"
      endpoint: /example
      method: POST